FACE_TYPE_SKY = -4
FACE_TYPE_GROUND = -3
FACE_TYPE_EDGE = -2
FACE_TYPE_EMPTY = -1
FACE_TYPE_OUTSIDE = 0
FACE_TYPE_WALL = 1
FACE_TYPE_DOOR = 2
FACE_TYPE_INSIDE = 3

FACE_TYPES = [FACE_TYPE_OUTSIDE, FACE_TYPE_WALL, FACE_TYPE_DOOR, FACE_TYPE_INSIDE]

FACE_PX = 0
FACE_PY = 1
FACE_NX = 2
FACE_NY = 3
FACE_PZ = 4
FACE_NZ = 5
FACES = [FACE_PX, FACE_PY, FACE_NX, FACE_NY, FACE_PZ]

PATTERN_OUTSIDE = "00000"
